In [9]:
import pandas as pd

df = pd.read_csv('../data/dirtydata.csv', encoding="utf-8")

df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [10]:
pd.get_dummies(df['Duration'])

    30   45   60   450
0     0    0    1    0
1     0    0    1    0
2     0    0    1    0
3     0    1    0    0
4     0    1    0    0
5     0    0    1    0
6     0    0    1    0
7     0    0    0    1
8     1    0    0    0
9     0    0    1    0
10    0    0    1    0
11    0    0    1    0
12    0    0    1    0
13    0    0    1    0
14    0    0    1    0
15    0    0    1    0
16    0    0    1    0
17    0    0    1    0
18    0    1    0    0
19    0    0    1    0
20    0    1    0    0
21    0    0    1    0
22    0    1    0    0
23    0    0    1    0
24    0    1    0    0
25    0    0    1    0
26    0    0    1    0
27    0    0    1    0
28    0    0    1    0
29    0    0    1    0
30    0    0    1    0
31    0    0    1    0

# binning

In [12]:
# labels에 원래는 0,1같이 숫자 넣어야함
bins = [df['Maxpulse'].min(), 120, df['Maxpulse'].max()]
df['MaxP'] = pd.cut(x = df['Maxpulse'], bins = bins, labels = ['Low', 'High'])
df

    Duration          Date  Pulse  Maxpulse  Calories  MaxP
0         60  '2020/12/01'    110       130     409.1  High
1         60  '2020/12/02'    117       145     479.0  High
2         60  '2020/12/03'    103       135     340.0  High
3         45  '2020/12/04'    109       175     282.4  High
4         45  '2020/12/05'    117       148     406.0  High
5         60  '2020/12/06'    102       127     300.0  High
6         60  '2020/12/07'    110       136     374.0  High
7        450  '2020/12/08'    104       134     253.3  High
8         30  '2020/12/09'    109       133     195.1  High
9         60  '2020/12/10'     98       124     269.0  High
10        60  '2020/12/11'    103       147     329.3  High
11        60  '2020/12/12'    100       120     250.7   Low
12        60  '2020/12/12'    100       120     250.7   Low
13        60  '2020/12/13'    106       128     345.3  High
14        60  '2020/12/14'    104       132     379.3  High
15        60  '2020/12/15'     98       123     275.0  High
16        60  '2020/12/16'     98       120     215.2   Low
17        60  '2020/12/17'    100       120     300.0   Low
18        45  '2020/12/18'     90       112       NaN   Low
19        60  '2020/12/19'    103       123     323.0  High
20        45  '2020/12/20'     97       125     243.0  High
21        60  '2020/12/21'    108       131     364.2  High
22        45           NaN    100       119     282.0   Low
23        60  '2020/12/23'    130       101     300.0   NaN
24        45  '2020/12/24'    105       132     246.0  High
25        60  '2020/12/25'    102       126     334.5  High
26        60      20201226    100       120     250.0   Low
27        60  '2020/12/27'     92       118     241.0   Low
28        60  '2020/12/28'    103       132       NaN  High
29        60  '2020/12/29'    100       132     280.0  High
30        60  '2020/12/30'    102       129     380.3  High
31        60  '2020/12/31'     92       115     243.0   Low

In [15]:
bins = [df['Calories'].min(), 320, df['Calories'].max()]
df['avCal'] = pd.cut(x = df['Calories'], bins = bins, labels = [1, 2])
df

    Duration          Date  Pulse  Maxpulse  Calories  MaxP avCal
0         60  '2020/12/01'    110       130     409.1  High     2
1         60  '2020/12/02'    117       145     479.0  High     2
2         60  '2020/12/03'    103       135     340.0  High     2
3         45  '2020/12/04'    109       175     282.4  High     1
4         45  '2020/12/05'    117       148     406.0  High     2
5         60  '2020/12/06'    102       127     300.0  High     1
6         60  '2020/12/07'    110       136     374.0  High     2
7        450  '2020/12/08'    104       134     253.3  High     1
8         30  '2020/12/09'    109       133     195.1  High   NaN
9         60  '2020/12/10'     98       124     269.0  High     1
10        60  '2020/12/11'    103       147     329.3  High     2
11        60  '2020/12/12'    100       120     250.7   Low     1
12        60  '2020/12/12'    100       120     250.7   Low     1
13        60  '2020/12/13'    106       128     345.3  High     2
14        60  '2020/12/14'    104       132     379.3  High     2
15        60  '2020/12/15'     98       123     275.0  High     1
16        60  '2020/12/16'     98       120     215.2   Low     1
17        60  '2020/12/17'    100       120     300.0   Low     1
18        45  '2020/12/18'     90       112       NaN   Low   NaN
19        60  '2020/12/19'    103       123     323.0  High     2
20        45  '2020/12/20'     97       125     243.0  High     1
21        60  '2020/12/21'    108       131     364.2  High     2
22        45           NaN    100       119     282.0   Low     1
23        60  '2020/12/23'    130       101     300.0   NaN     1
24        45  '2020/12/24'    105       132     246.0  High     1
25        60  '2020/12/25'    102       126     334.5  High     2
26        60      20201226    100       120     250.0   Low     1
27        60  '2020/12/27'     92       118     241.0   Low     1
28        60  '2020/12/28'    103       132       NaN  High   NaN
29        60  '2020/12/29'    100       132     280.0  High     1
30        60  '2020/12/30'    102       129     380.3  High     2
31        60  '2020/12/31'     92       115     243.0   Low     1